const i18n={ru:{loading:'Загрузка кибер-портфолио...',navAbout:'Обо мне',navProjects:'Проекты',navPlayground:'Песочница',navContacts:'Контакты',heroBadge:'Senior Fullstack • Motion UI',heroTitle:'Создаю вау-эффект в вебе и продуктовый код.',heroSubtitle:'Больше интерактива, анимаций и технологичности — в одном портфолио.',ctaProjects:'Смотреть проекты',ctaCat:'Вызвать котика',aboutTitle:'Обо мне',aboutText:'Проектирую и собираю продукты: от UI-концепта до production.',projectsTitle:'Проекты',playTitle:'Live Playground',runCode:'Запустить код',contactsTitle:'Контакты',send:'Отправить',reviewsTitle:'Отзывы'},en:{loading:'Loading cyber portfolio...',navAbout:'About',navProjects:'Projects',navPlayground:'Playground',navContacts:'Contacts',heroBadge:'Senior Fullstack • Motion UI',heroTitle:'I build wow-level web experiences and production code.',heroSubtitle:'More interactivity, animation, and IT power in one portfolio.',ctaProjects:'View projects',ctaCat:'Spawn cat',aboutTitle:'About me',aboutText:'I design and ship products from UI concept to production.',projectsTitle:'Projects',playTitle:'Live Playground',runCode:'Run code',contactsTitle:'Contacts',send:'Send',reviewsTitle:'Reviews'},zh:{loading:'正在加载赛博作品集...',navAbout:'关于',navProjects:'项目',navPlayground:'代码沙盒',navContacts:'联系',heroBadge:'高级全栈 • 动效 UI',heroTitle:'打造惊艳网页体验与生产级代码。',heroSubtitle:'更强互动、更炫动画、更高 IT 质感。',ctaProjects:'查看项目',ctaCat:'召唤猫咪',aboutTitle:'关于我',aboutText:'从 UI 概念到上线交付，我负责完整产品实现。',projectsTitle:'项目',playTitle:'实时沙盒',runCode:'运行代码',contactsTitle:'联系',send:'发送',reviewsTitle:'评价'}};
const DATA_PATH='./data.json';
const $=(s)=>document.querySelector(s); const $$=(s)=>document.querySelectorAll(s);
const state={lang:localStorage.getItem('portfolioLang')||'ru'};
function t(k){return i18n[state.lang][k]||k}
function applyI18n(){$$('[data-i18n]').forEach((el)=>el.textContent=t(el.dataset.i18n));typeTitle(t('heroTitle'));}
function typeTitle(text){const e=$('#typingTitle');e.textContent='';[...text].forEach((c,i)=>setTimeout(()=>e.textContent+=c,20*i));}
function setupUI(){ $('#langSelect').value=state.lang; $('#langSelect').addEventListener('change',(e)=>{state.lang=e.target.value;localStorage.setItem('portfolioLang',state.lang);applyI18n();}); $('#navToggle').addEventListener('click',()=>$('#navLinks').classList.toggle('open')); $$('#navLinks a').forEach(a=>a.addEventListener('click',()=>$('#navLinks').classList.remove('open'))); const ob=new IntersectionObserver((es)=>es.forEach(x=>x.isIntersecting&&x.target.classList.add('visible')),{threshold:.15}); $$('.reveal').forEach(el=>ob.observe(el)); $('#spawnCat').addEventListener('click',()=>{const c=$('#catEaster');c.classList.add('show');setTimeout(()=>c.classList.remove('show'),4200);}); }
async function renderData(){const data=await (await fetch(DATA_PATH)).json();const pg=$('#projectsGrid');pg.innerHTML='';data.projects.forEach(p=>{const n=$('#projectTemplate').content.cloneNode(true);n.querySelector('h3').textContent=p.title;n.querySelector('.project-description').textContent=p.description;n.querySelector('.project-image').src=p.image;const tags=n.querySelector('.project-tags');(p.tags||[]).forEach(tag=>{const s=document.createElement('span');s.textContent=tag;tags.append(s)});pg.append(n)});const rv=$('#reviewsList');rv.innerHTML='';data.reviews.forEach(r=>{const n=$('#reviewTemplate').content.cloneNode(true);n.querySelector('.review-text').textContent=`“${r.text}”`;n.querySelector('.review-author').textContent=r.author;n.querySelector('.review-role').textContent=r.role;rv.append(n)});}
function setupPlay(){const demo=`<style>body{font-family:system-ui;padding:16px;background:#0b1025;color:#fff}button{padding:8px 12px;border:0;border-radius:8px;background:#7b5cff;color:#fff}</style><h2>Cyber Lab</h2><button onclick="document.body.style.background='#102b18'">Hack mode</button>`;$('#codeInput').value=demo;const run=()=>$('#codePreview').srcdoc=$('#codeInput').value;$('#runCodeBtn').addEventListener('click',run);run();}
function setupForm(){$('#contactForm').addEventListener('submit',(e)=>{e.preventDefault();const p=Object.fromEntries(new FormData($('#contactForm')).entries());if(!p.name||!p.email||!p.message){$('#formStatus').textContent='Fill all fields';return;}const arr=JSON.parse(localStorage.getItem('messages')||'[]');arr.push({...p,date:new Date().toISOString()});localStorage.setItem('messages',JSON.stringify(arr));$('#formStatus').textContent='Saved!';$('#contactForm').reset();});}
window.addEventListener('load',()=>setTimeout(()=>$('#preloader').classList.add('hide'),900));
setupUI();applyI18n();renderData();setupPlay();setupForm();
